<?php

namespace App\Console\Commands;

use App\Events\Task\TaskUpdated;
use Illuminate\Console\Command;
use App\Models\Task;

class CreateMissingChunks extends Command
{
    protected $signature = 'tasks:chunk-missing';
    protected $description = 'Generate missing chunks for tasks';

    public function handle()
    {
        // Fetch all tasks without a chunk, eager-load relationships
        $tasks = Task::doesntHave('chunk')
            ->with(['user', 'tasklist.workspace'])
            ->get();

        // Summary info
        $userCount = $tasks->pluck('user.id')->unique()->count();
        $workspaceCount = $tasks->pluck('tasklist.workspace.id')->unique()->count();
        $taskCount = $tasks->count();

        $summary = [
            'users' => "$userCount user(s) with chunk missing",
            'workspaces' => "$workspaceCount workspace(s) with missing chunks",
            'tasks' => "total of $taskCount tasks with missing chunks",
        ];

        $this->info(json_encode($summary, JSON_PRETTY_PRINT));

        $this->line("");

        // Nested group processing: user -> workspace -> list -> task
        $tasks->groupBy('user.id')->each(function ($userTasks) {
            $userName = $userTasks->first()->user->name;

            $this->info("Processing User: {$userName}");

            $userTasks->groupBy(fn($t) => $t->tasklist->workspace->id)->each(function ($workspaceTasks) {
                $workspaceName = $workspaceTasks->first()->tasklist->workspace->name;

                $this->line("");
                $this->info("  Workspace: {$workspaceName}");

                $workspaceTasks->groupBy('tasklist_id')->each(function ($listTasks) {
                    $listName = $listTasks->first()->tasklist->name;
                    $this->info("    List: {$listName}");

                    foreach ($listTasks->sortBy('order') as $task) {
                        event(new TaskUpdated($task));
                    }
                });
            });
        });

        $this->info('Missing chunks processed. Tags will be generated by the AI API and updated in MySQL. Track progress in Phoenix UI.');
    }
}
