<?php

namespace App\Console\Commands;

use App\Events\Task\TaskUpdated;
use Illuminate\Console\Command;
use App\Models\Task;

class CreateMissingChunks extends Command
{
    protected $signature = 'tasks:chunk-missing {--user_id=} {--preview}';
    protected $description = 'Generate missing chunks for tasks';

    public function handle()
    {
        $userId = $this->option('user_id');
        $preview = $this->option('preview');

        $query = Task::query()
            ->where(function ($q) {
                $q->whereDoesntHave('chunk')
                    ->orWhereHas('chunk', function ($query) {
                        $query->withoutEmbedding();
                    });
            })
            ->with(['user', 'tasklist.workspace']);

        // Apply filter only if user_id is provided
        if ($userId) {
            $query->where('user_id', $userId);
            $this->info("Filtering by user_id: {$userId}");
        }

        $tasks = $query->get();

        // Summary info
        $userCount = $tasks->pluck('user.id')->unique()->count();
        $workspaceCount = $tasks->pluck('tasklist.workspace.id')->unique()->count();
        $taskCount = $tasks->count();

        $summary = [
            'users' => "$userCount user(s) with chunk missing",
            'workspaces' => "$workspaceCount workspace(s) with missing chunks",
            'tasks' => "total of $taskCount tasks with missing chunks",
        ];

        $this->info(json_encode($summary, JSON_PRETTY_PRINT));
        $this->line("");

        if ($preview) {
            $this->info("Preview mode enabled. No events will be dispatched.");
            return;
        }

        // Nested group processing
        $tasks->groupBy('user.id')->each(function ($userTasks) {
            $userName = $userTasks->first()->user->name;

            $this->info("Processing User: {$userName}");

            $userTasks->groupBy(fn($t) => $t->tasklist->workspace->id)->each(function ($workspaceTasks) {
                $workspaceName = $workspaceTasks->first()->tasklist->workspace->name;

                $this->line("");
                $this->info("  Workspace: {$workspaceName}");

                $workspaceTasks->groupBy('tasklist_id')->each(function ($listTasks) {
                    $listName = $listTasks->first()->tasklist->name;
                    $this->info("    List: {$listName}");

                    foreach ($listTasks->sortBy('order') as $task) {
                        event(new TaskUpdated($task));
                    }
                });
            });
        });

        $this->info('Missing chunks processed. Tags will be generated by the AI API and updated in MySQL. Track progress in Phoenix UI.');
    }
}
